source 'git@gitlab.317hu.com:HuModularizationLibrary/HuModularizationSpecs.git'
source 'https://github.com/CocoaPods/Specs.git'

target 'WGFileDemixionKit_Example' do
  pod 'WGFileDemixionKit', :path => '../'

  target 'WGFileDemixionKit_Tests' do
    inherit! :search_paths

    
  end
end
